/* DFIR reference data — static, no network calls. Edit freely. */
window.DFIR_DATA = [
  {
    id: "http",
    title: "HTTP Status Codes",
    desc: "Common response codes seen in web logs, proxies, and API traffic during IR.",
    columns: ["Code", "Name", "Severity", "DFIR note"],
    rows: [
      ["100", "Continue", "info", "Client may send body; rare in logs."],
      ["101", "Switching Protocols", "info", "Upgrade (WebSocket, HTTP/2)."],
      ["200", "OK", "ok", "Success — baseline noise; check unusual volume."],
      ["201", "Created", "ok", "Resource created (POST/PUT)."],
      ["204", "No Content", "ok", "Success with empty body."],
      ["301", "Moved Permanently", "info", "SEO / redirect chains; phishing redirect patterns."],
      ["302", "Found", "info", "Temporary redirect; OAuth & open-redirect abuse."],
      ["304", "Not Modified", "ok", "Cache hit; normal browser noise."],
      ["307", "Temporary Redirect", "info", "Method preserved on redirect."],
      ["308", "Permanent Redirect", "info", "Method preserved permanent redirect."],
      ["400", "Bad Request", "warn", "Malformed req; scanners, WAF, API abuse."],
      ["401", "Unauthorized", "warn", "Auth missing/failed — brute force / spray."],
      ["403", "Forbidden", "warn", "Authz deny; dir bust, privilege fail."],
      ["404", "Not Found", "info", "Noise vs recon; spike = scanning."],
      ["405", "Method Not Allowed", "warn", "Wrong verb on endpoint."],
      ["408", "Request Timeout", "warn", "Slowloris-ish or network issues."],
      ["409", "Conflict", "warn", "State conflict (APIs, concurrent edits)."],
      ["413", "Payload Too Large", "warn", "Upload abuse / size limits."],
      ["429", "Too Many Requests", "warn", "Rate limit hit — bots, brute force."],
      ["500", "Internal Server Error", "err", "App fault; exploit probes may trigger."],
      ["502", "Bad Gateway", "err", "Upstream down; proxy/WAF path."],
      ["503", "Service Unavailable", "err", "Overload / maintenance / DoS impact."],
      ["504", "Gateway Timeout", "err", "Upstream too slow; cascading failure."]
    ]
  },
  {
    id: "dns",
    title: "DNS Response Codes (RCODE)",
    desc: "From packet captures, resolver logs, and passive DNS.",
    columns: ["Code", "Name", "Severity", "DFIR note"],
    rows: [
      ["0", "NOERROR", "ok", "Query answered (may still be empty ANSWER)."],
      ["1", "FORMERR", "warn", "Malformed query; broken client or fuzzing."],
      ["2", "SERVFAIL", "err", "Server failure; DNS outage or misconfig."],
      ["3", "NXDOMAIN", "info", "Name does not exist; DGA / recon / typo."],
      ["4", "NOTIMP", "warn", "Query type not implemented."],
      ["5", "REFUSED", "warn", "Policy refuse; ACLs, RPZ, blocked domain."],
      ["6", "YXDOMAIN", "info", "Name exists when it should not (UPDATE)."],
      ["9", "NOTAUTH", "warn", "Server not authoritative for zone."],
      ["16", "BADVERS / BADSIG", "warn", "EDNS/TSIG issues."],
      ["23", "BADCOOKIE", "warn", "DNS cookie validation failed."]
    ]
  },
  {
    id: "sysmon",
    title: "Sysmon Event IDs",
    desc: "Microsoft Sysmon (SwiftOnSecurity / Olaf Hartong configs). Core for Windows process & network IR.",
    columns: ["ID", "Event", "Severity", "DFIR note"],
    rows: [
      ["1", "Process Create", "info", "Command line, parent, hashes — primary timeline."],
      ["2", "File creation time changed", "warn", "Timestomping indicator."],
      ["3", "Network connection", "info", "Process → IP:port; C2 beaconing."],
      ["4", "Sysmon service state", "warn", "Sysmon stop/start — defense evasion."],
      ["5", "Process terminated", "info", "Pair with ID 1 for process life."],
      ["6", "Driver loaded", "warn", "Kernel drivers; rootkit risk."],
      ["7", "Image loaded", "info", "DLL load; injection / sideload hunting."],
      ["8", "CreateRemoteThread", "err", "Classic injection technique."],
      ["9", "RawAccessRead", "err", "Direct volume read — credential/dump tools."],
      ["10", "ProcessAccess", "warn", "OpenProcess; LSASS access (Mimikatz etc)."],
      ["11", "FileCreate", "info", "Dropped malware, scripts, tools."],
      ["12", "Registry object create/delete", "info", "Persistence keys appearing/removed."],
      ["13", "Registry value set", "warn", "Run keys, services, COM hijack values."],
      ["14", "Registry object renamed", "warn", "Evasion / cleanup."],
      ["15", "FileCreateStreamHash", "info", "ADS (Zone.Identifier) — download origin."],
      ["17", "PipeCreated", "info", "Named pipes; lateral & C2 IPC."],
      ["18", "PipeConnected", "info", "Who connected to the pipe."],
      ["19", "WmiEventFilter", "err", "WMI persistence filter."],
      ["20", "WmiEventConsumer", "err", "WMI consumer (payload)."],
      ["21", "WmiEventConsumerToFilter", "err", "Binds filter→consumer."],
      ["22", "DNS query", "info", "Process DNS; C2 domains, DoH clients."],
      ["23", "FileDelete (archived)", "warn", "Deleted file content saved if configured."],
      ["24", "Clipboard change", "info", "Rare; insider / malware clipboard."],
      ["25", "ProcessTampering", "err", "Process hollowing / herpaderping signals."],
      ["26", "FileDeleteDetected", "info", "Delete without archive."],
      ["27", "FileBlockExecutable", "warn", "Blocked exe write (config)."],
      ["28", "FileBlockShredding", "warn", "Secure-delete tools blocked."],
      ["29", "FileExecutableDetected", "info", "New PE written."],
      ["255", "Error", "err", "Sysmon internal error."]
    ]
  },
  {
    id: "winevt-sec",
    title: "Windows Security Event IDs",
    desc: "Security.evtx — auth, logon, account & privilege events.",
    columns: ["ID", "Event", "Severity", "DFIR note"],
    rows: [
      ["4624", "Successful logon", "info", "Type 2/3/10 critical; map LogonType."],
      ["4625", "Failed logon", "warn", "Spray / brute force; Status & SubStatus."],
      ["4634", "Logoff", "info", "Session end (often noisy)."],
      ["4648", "Logon with explicit credentials", "warn", "runas / lateral with alternate creds."],
      ["4672", "Special privileges assigned", "warn", "Admin logon (SeDebugPrivilege etc)."],
      ["4688", "Process creation", "info", "If cmd-line auditing enabled."],
      ["4697", "Service installed", "err", "Persistence via service."],
      ["4698", "Scheduled task created", "err", "Task persistence."],
      ["4699", "Scheduled task deleted", "warn", "Cleanup after use."],
      ["4702", "Scheduled task updated", "warn", "Modified task action/trigger."],
      ["4720", "User account created", "warn", "Rogue local account."],
      ["4722", "User account enabled", "warn", "Re-enabled dormant account."],
      ["4724", "Password reset attempt", "warn", "Account takeover path."],
      ["4728", "Member added to global group", "warn", "Privilege group changes."],
      ["4732", "Member added to local group", "err", "Local Administrators adds."],
      ["4738", "User account changed", "info", "Attribute changes."],
      ["4740", "Account locked out", "warn", "Spray side-effect or lockout attack."],
      ["4768", "Kerberos TGT requested", "info", "AS-REQ; DC logs."],
      ["4769", "Kerberos service ticket", "info", "TGS; hunt RC4 / rare SPNs."],
      ["4771", "Kerberos pre-auth failed", "warn", "Password spray against Kerberos."],
      ["4776", "NTLM credential validation", "info", "DC/server validated NTLM."],
      ["5140", "Network share accessed", "info", "Share connect; lateral movement."],
      ["5145", "Share object checked", "warn", "Detailed share access (noisy if on)."],
      ["7045", "Service installed (System)", "err", "Often in System log; malware services."]
    ]
  },
  {
    id: "logontype",
    title: "Windows Logon Types (4624/4625)",
    desc: "LogonType field interpretation for Security events.",
    columns: ["Type", "Name", "Severity", "DFIR note"],
    rows: [
      ["2", "Interactive", "info", "Console / local keyboard logon."],
      ["3", "Network", "info", "SMB, IIS, PsExec-like network logon."],
      ["4", "Batch", "warn", "Scheduled task batch logon."],
      ["5", "Service", "info", "Service account start."],
      ["7", "Unlock", "info", "Workstation unlock."],
      ["8", "NetworkCleartext", "warn", "IIS basic auth etc — creds in clear."],
      ["9", "NewCredentials", "warn", "runas /netonly — alternate creds."],
      ["10", "RemoteInteractive", "warn", "RDP / Terminal Services."],
      ["11", "CachedInteractive", "info", "Cached domain creds offline."]
    ]
  },
  {
    id: "ntstatus",
    title: "Windows Status / SubStatus (common)",
    desc: "Often in 4625 Status & SubStatus; also NTSTATUS in other logs.",
    columns: ["Code", "Name", "Severity", "DFIR note"],
    rows: [
      ["0x0", "STATUS_SUCCESS", "ok", "Success."],
      ["0xC0000064", "STATUS_NO_SUCH_USER", "warn", "Unknown username (spray enum)."],
      ["0xC000006A", "STATUS_WRONG_PASSWORD", "warn", "Bad password; valid user often."],
      ["0xC0000234", "STATUS_ACCOUNT_LOCKED_OUT", "warn", "Locked account."],
      ["0xC0000072", "STATUS_ACCOUNT_DISABLED", "warn", "Disabled account logon attempt."],
      ["0xC0000193", "STATUS_ACCOUNT_EXPIRED", "warn", "Expired account."],
      ["0xC0000224", "STATUS_PASSWORD_MUST_CHANGE", "info", "Must change password."],
      ["0xC000006F", "STATUS_INVALID_LOGON_HOURS", "warn", "Outside allowed hours."],
      ["0xC0000070", "STATUS_INVALID_WORKSTATION", "warn", "Workstation restriction."],
      ["0xC0000071", "STATUS_PASSWORD_EXPIRED", "warn", "Password expired."],
      ["0xC000015B", "STATUS_LOGON_TYPE_NOT_GRANTED", "warn", "Logon type not allowed."],
      ["0xC000006D", "STATUS_LOGON_FAILURE", "warn", "Generic logon failure."],
      ["0xC0000022", "STATUS_ACCESS_DENIED", "warn", "Access denied."],
      ["0xC0000005", "STATUS_ACCESS_VIOLATION", "err", "AV exception / crash / exploit."],
      ["0xC0000135", "STATUS_DLL_NOT_FOUND", "err", "Missing DLL — sideload / broken drop."],
      ["0xC0000139", "STATUS_ENTRYPOINT_NOT_FOUND", "err", "Bad import / corrupt PE."],
      ["0xC0000001", "STATUS_UNSUCCESSFUL", "warn", "Generic failure."]
    ]
  },
  {
    id: "win32",
    title: "Win32 Error Codes (common)",
    desc: "GetLastError / tools output during malware & host analysis.",
    columns: ["Code", "Name", "Severity", "DFIR note"],
    rows: [
      ["0", "ERROR_SUCCESS", "ok", "No error."],
      ["2", "ERROR_FILE_NOT_FOUND", "info", "Missing file path."],
      ["3", "ERROR_PATH_NOT_FOUND", "info", "Missing directory."],
      ["5", "ERROR_ACCESS_DENIED", "warn", "Permissions / AV / protected process."],
      ["32", "ERROR_SHARING_VIOLATION", "info", "File locked by another process."],
      ["87", "ERROR_INVALID_PARAMETER", "warn", "Bad API args; buggy malware."],
      ["122", "ERROR_INSUFFICIENT_BUFFER", "info", "Buffer too small (common in API loops)."],
      ["267", "ERROR_DIRECTORY", "info", "Expected file, got directory (or vice versa)."],
      ["1058", "ERROR_SERVICE_DISABLED", "warn", "Service disabled."],
      ["1060", "ERROR_SERVICE_DOES_NOT_EXIST", "info", "Service name missing."],
      ["1314", "ERROR_PRIVILEGE_NOT_HELD", "warn", "Missing Se* privilege."],
      ["1326", "ERROR_LOGON_FAILURE", "warn", "Bad user/pass."],
      ["1327", "ERROR_ACCOUNT_RESTRICTION", "warn", "Policy restriction."],
      ["1331", "ERROR_ACCOUNT_DISABLED", "warn", "Disabled account."],
      ["1909", "ERROR_ACCOUNT_LOCKED_OUT", "warn", "Locked out."]
    ]
  },
  {
    id: "errno",
    title: "Linux errno (common)",
    desc: "Seen in strace, auditd, app logs on Linux endpoints.",
    columns: ["#", "Name", "Severity", "DFIR note"],
    rows: [
      ["1", "EPERM", "warn", "Operation not permitted."],
      ["2", "ENOENT", "info", "No such file or directory."],
      ["3", "ESRCH", "info", "No such process."],
      ["4", "EINTR", "info", "Interrupted system call."],
      ["5", "EIO", "err", "I/O error — disk / device issues."],
      ["9", "EBADF", "warn", "Bad file descriptor."],
      ["11", "EAGAIN / EWOULDBLOCK", "info", "Resource temporarily unavailable."],
      ["13", "EACCES", "warn", "Permission denied."],
      ["17", "EEXIST", "info", "File exists."],
      ["20", "ENOTDIR", "info", "Not a directory."],
      ["21", "EISDIR", "info", "Is a directory."],
      ["22", "EINVAL", "warn", "Invalid argument."],
      ["24", "EMFILE", "warn", "Too many open files (process)."],
      ["28", "ENOSPC", "err", "No space left on device."],
      ["32", "EPIPE", "info", "Broken pipe."],
      ["98", "EADDRINUSE", "warn", "Address already in use (bind)."],
      ["99", "EADDRNOTAVAIL", "warn", "Cannot assign requested address."],
      ["110", "ETIMEDOUT", "warn", "Connection timed out."],
      ["111", "ECONNREFUSED", "warn", "Connection refused."],
      ["113", "EHOSTUNREACH", "warn", "No route to host."]
    ]
  },
  {
    id: "exit",
    title: "Process Exit Codes",
    desc: "Shell, scripts, and service managers — quick read of failure class.",
    columns: ["Code", "Meaning", "Severity", "DFIR note"],
    rows: [
      ["0", "Success", "ok", "Normal completion."],
      ["1", "General error", "warn", "Catch-all failure."],
      ["2", "Misuse of shell builtins", "warn", "Bad args (bash)."],
      ["126", "Not executable", "warn", "Permission / not a program."],
      ["127", "Command not found", "warn", "PATH miss / deleted binary."],
      ["128", "Invalid exit argument", "info", "Exit code out of range."],
      ["128+N", "Killed by signal N", "err", "e.g. 137 = 128+9 SIGKILL; 139 = SIGSEGV."],
      ["130", "SIGINT (Ctrl+C)", "info", "128+2."],
      ["137", "SIGKILL", "err", "128+9 — OOM killer or kill -9."],
      ["139", "SIGSEGV", "err", "128+11 — crash / possible exploit."],
      ["143", "SIGTERM", "warn", "128+15 — graceful kill."],
      ["255", "Out of range / exit -1", "warn", "Often wrapper or fatal script error."]
    ]
  },
  {
    id: "tcp",
    title: "TCP Flags & States (quick)",
    desc: "Packet analysis shorthand for Wireshark / tcpdump / Zeek.",
    columns: ["Flag/State", "Meaning", "Severity", "DFIR note"],
    rows: [
      ["SYN", "Synchronize", "info", "New connection attempt; scan if many."],
      ["ACK", "Acknowledge", "info", "Part of established flow."],
      ["FIN", "Finish", "info", "Graceful close."],
      ["RST", "Reset", "warn", "Abort; port closed, RST scan, inject."],
      ["PSH", "Push", "info", "Push data to app immediately."],
      ["URG", "Urgent", "warn", "Rare legitimately; odd in malware."],
      ["SYN+ACK", "Listen accept", "info", "Open port response."],
      ["FIN+ACK", "Close handshake", "info", "Normal teardown piece."],
      ["RST+ACK", "Reject/abort", "warn", "Common on closed/filtered."],
      ["LISTEN", "Waiting for SYN", "info", "Local open port."],
      ["ESTABLISHED", "Connected", "info", "Active session — C2 candidate."],
      ["TIME_WAIT", "Post-close wait", "info", "Normal; high count = churn."],
      ["CLOSE_WAIT", "Remote closed, local app lag", "warn", "App not closing; leak / hang."]
    ]
  },
  {
    id: "ports",
    title: "Ports — DFIR Hotlist",
    desc: "Not exhaustive. Focus on lateral movement, C2, and admin protocols.",
    columns: ["Port", "Service", "Severity", "DFIR note"],
    rows: [
      ["20/21", "FTP data/ctrl", "warn", "Cleartext file transfer."],
      ["22", "SSH", "info", "Admin access; brute force target."],
      ["23", "Telnet", "err", "Cleartext remote shell — legacy risk."],
      ["25/587", "SMTP", "info", "Mail exfil / phishing infra."],
      ["53", "DNS", "info", "Tunneling (iodine, dns2tcp); DGA."],
      ["80/443", "HTTP/HTTPS", "info", "C2 over web; look beyond port."],
      ["88", "Kerberos", "info", "Auth to AD; ticket attacks."],
      ["110/995", "POP3", "info", "Mail access."],
      ["135", "MSRPC", "warn", "Windows RPC endpoint mapper."],
      ["139", "NetBIOS SSB", "warn", "Legacy SMB path."],
      ["143/993", "IMAP", "info", "Mail access."],
      ["161/162", "SNMP", "warn", "Community strings; recon."],
      ["389/636", "LDAP/LDAPS", "info", "Directory; enumeration."],
      ["445", "SMB", "err", "Lateral (PsExec, wormable hist)."],
      ["464", "Kerberos passwd", "info", "Password change."],
      ["514", "Syslog", "info", "Often UDP cleartext logs."],
      ["993", "IMAPS", "info", "Encrypted IMAP."],
      ["1433", "MSSQL", "warn", "DB; xp_cmdshell abuse."],
      ["1521", "Oracle", "warn", "DB listener."],
      ["2049", "NFS", "warn", "File share; misconfig exposure."],
      ["3306", "MySQL", "warn", "DB remote access."],
      ["3389", "RDP", "err", "Remote desktop; brute / BlueKeep era."],
      ["5432", "PostgreSQL", "warn", "DB."],
      ["5900", "VNC", "err", "Remote GUI; often weak auth."],
      ["5985/5986", "WinRM HTTP/S", "err", "PowerShell remoting lateral."],
      ["6379", "Redis", "warn", "Unauth Redis = RCE history."],
      ["8080/8443", "Alt HTTP(S)", "info", "Admin panels, proxies, C2."],
      ["27017", "MongoDB", "warn", "Often exposed unauth historically."]
    ]
  },
  {
    id: "magic",
    title: "File Magic / Signatures",
    desc: "Header bytes for triage when extensions lie (xxd, file, hex editors).",
    columns: ["Hex / ASCII", "Format", "Severity", "DFIR note"],
    rows: [
      ["4D 5A (MZ)", "PE / DOS exe", "info", "Windows PE; check PE header at e_lfanew."],
      ["50 45 00 00 (PE)", "PE signature", "info", "At offset from MZ e_lfanew."],
      ["7F 45 4C 46 (ELF)", "ELF binary", "info", "Linux/Unix executable/SO."],
      ["CA FE BA BE", "Mach-O fat / Java class", "info", "Context matters (macOS vs .class)."],
      ["CE FA ED FE / CF FA ED FE", "Mach-O 32/64", "info", "macOS binaries."],
      ["25 50 44 46 (%PDF)", "PDF", "info", "Phish docs; check JS / streams."],
      ["50 4B 03 04 (PK)", "ZIP / OOXML / JAR", "info", "docx/xlsx/pptx/apk also ZIP."],
      ["52 61 72 21 (Rar!)", "RAR", "info", "Archive; often malware drop."],
      ["1F 8B", "GZIP", "info", "Compressed; often .gz / nested."],
      ["42 5A 68 (BZh)", "BZIP2", "info", "Compressed."],
      ["37 7A BC AF 27 1C", "7z", "info", "7-Zip archive."],
      ["89 50 4E 47", "PNG", "info", "Image; stego possible."],
      ["FF D8 FF", "JPEG", "info", "Image."],
      ["47 49 46 38 (GIF8)", "GIF", "info", "Image; polyglot history."],
      ["52 49 46 46 (RIFF)", "WAV/AVI/WebP", "info", "Check form type bytes 8+."],
      ["00 00 00 xx 66 74 79 70", "MP4/MOV", "info", "ftyp box — media."],
      ["4F 67 67 53 (OggS)", "Ogg", "info", "Container."],
      ["7B 5C 72 74 66 ({\\rtf)", "RTF", "warn", "Legacy Office exploit path."],
      ["D0 CF 11 E0", "OLE CFBF", "warn", "doc/xls/ppt classic; macros."],
      ["53 51 4C 69 74 65", "SQLite", "info", "Browser/history DBs."],
      ["4C 00 00 00 01 14 02", "LNK", "warn", "Windows shortcut; payload path."],
      ["45 52 46 53 53 (EVTX partial)", "EVTX related", "info", "Use proper parsers for .evtx."],
      ["72 65 67 66 (regf)", "Registry hive", "info", "SYSTEM/SOFTWARE/NTUSER hives."]
    ]
  },
  {
    id: "http-methods",
    title: "HTTP Methods",
    desc: "Access logs & proxies — unusual methods stand out.",
    columns: ["Method", "Role", "Severity", "DFIR note"],
    rows: [
      ["GET", "Read resource", "info", "Default noise; exfil via query strings."],
      ["POST", "Submit body", "info", "C2 beacons, uploads, auth."],
      ["PUT", "Store/replace", "warn", "Web shells / upload if misconfigured."],
      ["PATCH", "Partial update", "info", "REST APIs."],
      ["DELETE", "Remove", "warn", "Destructive API abuse."],
      ["HEAD", "Headers only", "info", "Scanners / availability checks."],
      ["OPTIONS", "CORS preflight", "info", "Recon of allowed methods."],
      ["CONNECT", "Tunnel (proxy)", "warn", "Proxy abuse; MITM path."],
      ["TRACE", "Echo request", "warn", "XST risk; usually disabled."],
      ["PROPFIND", "WebDAV", "warn", "WebDAV recon / exploit paths."]
    ]
  },
  {
    id: "smb",
    title: "SMB / NT Status (share access)",
    desc: "Common when reviewing lateral movement and share enumeration.",
    columns: ["Code", "Name", "Severity", "DFIR note"],
    rows: [
      ["0x0", "SUCCESS", "ok", "Access OK."],
      ["0xC0000022", "ACCESS_DENIED", "warn", "Share/file ACL deny."],
      ["0xC000000F", "NO_SUCH_FILE", "info", "Path missing."],
      ["0xC0000034", "OBJECT_NAME_NOT_FOUND", "info", "Name not found."],
      ["0xC000003A", "OBJECT_PATH_NOT_FOUND", "info", "Path not found."],
      ["0xC000006D", "LOGON_FAILURE", "warn", "Bad creds to share."],
      ["0xC000006E", "ACCOUNT_RESTRICTION", "warn", "Account restriction."],
      ["0xC0000023", "BUFFER_TOO_SMALL", "info", "Client buffer sizing."],
      ["0xC00000BB", "NOT_SUPPORTED", "info", "Dialect/feature unsupported."],
      ["0xC00000CC", "BAD_NETWORK_NAME", "warn", "Share name invalid."],
      ["0xC0000203", "USER_SESSION_DELETED", "warn", "Session torn down."]
    ]
  },
  {
    id: "browser",
    title: "Browser Artifact Paths (quick)",
    desc: "Where to look first on disk — not error codes, but daily DFIR muscle memory.",
    columns: ["Item", "Location (typical)", "Severity", "DFIR note"],
    rows: [
      ["Chrome History", "%LocalAppData%/Google/Chrome/User Data/Default/History", "info", "SQLite; URLs, visits."],
      ["Chrome Cookies", ".../Default/Network/Cookies (or Cookies)", "info", "SQLite; session theft."],
      ["Chrome Login Data", ".../Default/Login Data", "warn", "Saved passwords (encrypted)."],
      ["Chrome Cache", ".../Default/Cache", "info", "Cached objects."],
      ["Firefox places", "%AppData%/Mozilla/Firefox/Profiles/<p>/places.sqlite", "info", "History/bookmarks."],
      ["Edge History", "%LocalAppData%/Microsoft/Edge/User Data/Default/History", "info", "Chromium-based."],
      ["Zone.Identifier", "file:Zone.Identifier ADS", "info", "Mark-of-the-Web; download URL."],
      ["Prefetch", "C:\\Windows\\Prefetch\\*.pf", "info", "Exec evidence (Windows)."],
      ["Amcache", "…/AppCompat/Programs/Amcache.hve", "info", "Program execution."],
      ["Shimcache", "SYSTEM hive AppCompatCache", "info", "Evidence of existence/exec."],
      ["$MFT", "NTFS Master File Table", "info", "Filesystem timeline backbone."],
      ["bash history", "~/.bash_history", "info", "Linux command history."],
      ["zsh history", "~/.zsh_history", "info", "Zsh history."],
      ["auth.log", "/var/log/auth.log or secure", "info", "SSH & sudo on Linux."]
    ]
  },
  {
    id: "tls-alerts",
    title: "TLS Alert Descriptions (common)",
    desc: "Seen in packet captures when handshakes fail.",
    columns: ["Code", "Alert", "Severity", "DFIR note"],
    rows: [
      ["0", "close_notify", "info", "Clean TLS close."],
      ["10", "unexpected_message", "warn", "Protocol confusion."],
      ["20", "bad_record_mac", "warn", "Integrity fail; MITM/corruption."],
      ["40", "handshake_failure", "warn", "No cipher/version agreement."],
      ["42", "bad_certificate", "warn", "Cert corrupt/invalid."],
      ["43", "unsupported_certificate", "warn", "Type not supported."],
      ["44", "certificate_revoked", "err", "Revoked cert."],
      ["45", "certificate_expired", "warn", "Expired cert."],
      ["46", "certificate_unknown", "warn", "Other cert issue."],
      ["47", "illegal_parameter", "warn", "Bad handshake field."],
      ["48", "unknown_ca", "warn", "Untrusted CA — self-signed C2?"],
      ["49", "access_denied", "warn", "Cert auth denied."],
      ["51", "decode_error", "warn", "Message decode fail."],
      ["70", "protocol_version", "warn", "Version not supported."],
      ["80", "internal_error", "err", "Stack internal failure."],
      ["86", "inappropriate_fallback", "warn", "TLS_FALLBACK_SCSV triggered."],
      ["90", "user_canceled", "info", "User cancelled handshake."],
      ["112", "unrecognized_name", "warn", "SNI mismatch (virtual host)."],
      ["116", "certificate_required", "warn", "Client cert required."]
    ]
  },
  {
    id: "http-headers",
    title: "HTTP Headers worth hunting",
    desc: "Proxy and app logs — suspicious or high-value fields.",
    columns: ["Header", "Why it matters", "Severity", "DFIR note"],
    rows: [
      ["User-Agent", "Client fingerprint", "info", "Odd UA = scanners, tools, C2."],
      ["Authorization", "Creds / tokens", "warn", "Basic base64; Bearer tokens."],
      ["Cookie", "Session state", "warn", "Session hijack / fixation."],
      ["X-Forwarded-For", "Client IP chain", "info", "Spoofable; still useful."],
      ["X-Real-IP", "Proxy client IP", "info", "Same caveats as XFF."],
      ["Referer", "Navigation source", "info", "Phish landing paths."],
      ["Origin", "CORS origin", "info", "Cross-origin API abuse."],
      ["Host", "Target vhost", "info", "Routing & SSRF clues."],
      ["Content-Type", "Body type", "info", "Mismatch may mean smuggling."],
      ["Transfer-Encoding", "Chunked etc", "warn", "HTTP request smuggling."],
      ["Range", "Partial content", "info", "Scanner / download resume."],
      ["Accept-Language", "Locale", "info", "Weak geo/persona signal."]
    ]
  }
];
